version: "3"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb+srv://apurbapatra12:apurbaP@Cluster0.dovgxio.mongodb.net/
      - DB_NAME=ecommerce
    volumes:
      - ./app:/app/app
