services:
  - type: web
    name: hroneassignment-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DB_NAME
        sync: false
